lab1 -- Design fixes

diff --git a/1/server/Makefile b/1/server/Makefile
--- a/1/server/Makefile
+++ b/1/server/Makefile
@@ -1,30 +1,31 @@
 DEFINES = -D_POSIX_C_SOURCE -D_BSD_SOURCE
 CFLAGS  = -std=c99 -O2 -g $(DEFINES)
 LIBS    = -lpthread -lm
+TARGET  = server
 
-all: additionalLibCheck server cleanTemp
+all: additionalLibCheck $(TARGET) cleanTemp
 
 additionalLibCheck:
-	@(test -f list.h || test -f list.c) || ( \
-		echo "Missing list data structure!"; \
-		echo "Download at: https://github.com/alecsmirnov/doubly-linked-list" "\n"; \
-		exit 1; \
+	@(test -f list.h || test -f list.c) || ( 										\
+		echo "Missing list data structure!"; 										\
+		echo "Download at: https://github.com/alecsmirnov/doubly-linked-list" "\n";	\
+		exit 1; 																	\
 	)
-
-server: server_main.o server.o list.o
-	gcc $(CFLAGS) -o server server_main.o server.o list.o $(LIBS)
-
-server_main.o: server_main.c server.h
-	gcc $(CFLAGS) -c server_main.c
-
-server.o: server.c server.h list.h
-	gcc $(CFLAGS) -c server.c 
 
 list.o: list.c list.h
 	gcc $(CFLAGS) -c list.c
+
+$(TARGET): $(TARGET)_main.o $(TARGET).o list.o
+	gcc $(CFLAGS) -o $(TARGET) $(TARGET)_main.o $(TARGET).o list.o $(LIBS)
+
+$(TARGET)_main.o: $(TARGET)_main.c $(TARGET).h
+	gcc $(CFLAGS) -c $(TARGET)_main.c
+
+$(TARGET).o: $(TARGET).c $(TARGET).h list.h
+	gcc $(CFLAGS) -c $(TARGET).c
 
 cleanTemp:
 	rm -rf *.o
 
 clean:
-	rm -rf *.o server
+	rm -rf $(TARGET)
