lab1 -- Correcting the request header and checking the additional library

diff --git a/1/server/Makefile b/1/server/Makefile
--- a/1/server/Makefile
+++ b/1/server/Makefile
@@ -1,8 +1,15 @@
 DEFINES = -D_POSIX_C_SOURCE -D_BSD_SOURCE
-CFLAGS  = -std=c99 -02 -g $(DEFINES)
+CFLAGS  = -std=c99 -O2 -g $(DEFINES)
 LIBS    = -lpthread -lm
 
-all: server cleanTemp
+all: additionalLibCheck server cleanTemp
+
+additionalLibCheck:
+	@(test -f list.h || test -f list.c) || ( \
+		echo "Missing list data structure!"; \
+		echo "Download at: https://github.com/alecsmirnov/doubly-linked-list" "\n"; \
+		exit 1; \
+	)
 
 server: server_main.o server.o list.o
 	gcc $(CFLAGS) -o server server_main.o server.o list.o $(LIBS)
@@ -21,3 +28,5 @@ cleanTemp:
 
 clean:
 	rm -rf *.o server
+
+# list data structure from: https://github.com/alecsmirnov/doubly-linked-list
